apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-text-processing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-text-processing
  template:
    metadata:
      labels:
        app: python-text-processing
    spec:
      containers:
      - name: python-text-processing-container
        image: python-text-processing:latest  # Specify the correct tag for your image
        ports:
        - containerPort: 80
